name: github-pages

on: [push]

jobs:
  build-my-resume-and-deploy-it:
    runs-on: ubuntu-latest
    steps:
      - name: check-out-a-copy
        uses: actions/checkout@v2.3.1

      - name: Install and Build 
      - run: docker build -t resume .
      - run: docker run resume

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: resume
          folder: CV
