name: github-pages

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: deploy-resume-to-github-pages
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
    
    - name: Deploy resume
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: resume
        FOLDER: CV
