name: upgrade-while-push

on: [push]

jobs:
  build-my-resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check-out-a-copy
      - run: docker build -t resume .
      - run: docker run resume
