name: upgrade-while-push

on: [push]

jobs:
  build-my-resume:
    runs-on: ubuntu-latest
    steps:
      - name: check-out-a-copy
        uses: actions/checkout@v2
      - run: docker build --tag resume -f DockerFile .
      - run: docker run resume
